[package]
name = "mh_z19b"
version = "0.1.0"
authors = ["Peter Holak"]
edition = "2018"

[features]
default = ["serialport"]

[dependencies]
serialport = { version = "3.2.0", optional = true }

[dev-dependencies]
mockstream = "0.0.3"
